AppWeb/ViewModels/ColisViewModel.cs
using ClassLibrary;
using System;

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace AppWeb.ViewModels
{
    public class ColisViewModel
    {

        
        [DisplayName("Code Colis")]
        public int Colisid { get; set; }

        [DisplayName("Details")]
        public string detailsColis { get; set; }

        [DisplayName("Type")]
        public int typecolisid { get; set; }

        [DisplayName("Nature")]
        public int naturecolisid { get; set; }

        [DataType(DataType.Currency)]
        [Range(typeof(decimal), "0", "999999999999")]
        [DisplayName("Prix")]
        public decimal prixColis { get; set; }

        [DisplayName("État")]
        public string etatColis { get; set; }

        [DisplayName("Localisation")]
        public string localisation { get; set; }


        public DateTime date { get; set; }

        [DisplayName("Client")]
        public int clientid { get; set; }

        [DisplayName("Nom destinateire")]
        public string nomDestinateire { get; set; }

        [MaxLength(13, ErrorMessage = "Maximum {0} caractères")]
        [DisplayName("Téléphone destinateire")]
        public string telDestinataire { get; set; }

        [DisplayName("Adresse destinateire")]
        public string adresseDestinaraire { get; set; }

        [DisplayName("Ville de depart")]
        public int villeDepartColisid { get; set; }

        [DisplayName("Ville d'arrive")]
        public int villeArriveColisid { get; set; }
        
        [DisplayName("Date Depart")]
        public string dateDepartColis { get; set; }

        
        [DisplayName("Date Arrivé")]
        public string dateArriveColis { get; set; }

        [DisplayName("Voie de transmission")]
        public int voietransmissionid { get; set; }

        public virtual TypeColis Type { get; set; }
        public virtual Client Client { get; set; }
        public virtual NatureColis Nature { get; set; }
        public virtual VoieTransmission Voie { get; set; }
        public virtual Ville villeArriveColis { get; set; }
        public virtual Ville villeDepartColis { get; set; }

        /*
        
        [Key]
        [DisplayName("Code Colis")]
        public int Colisid { get; set; }

        [DisplayName("Details")]
        [MaxLength(150, ErrorMessage = "Maximum {0} caractères")]
        public string detailsColis { get; set; }

        [DisplayName("Type")]
        [Required(ErrorMessage = "Rempliez le champ Type")]
        public int typecolisid { get; set; }

        [DisplayName("Nature")]
        [Required(ErrorMessage = "Rempliez le champ Nature")]
        public int naturecolisid { get; set; }


        [DisplayName("Prix")]
        [Required(ErrorMessage = "Rempliez le champ Prix")]
        [DataType(DataType.Currency)]
        [Range(typeof(decimal), "0", "999999999999")]
        public decimal prixColis { get; set; }

        [DisplayName("État")]
        [Required(ErrorMessage = "Rempliez le champ Etat")]
        [MaxLength(100, ErrorMessage = "Maximum {0} caractères")]
        public string etatColis { get; set; }

        [DisplayName("Localisation")]
         [MaxLength(100, ErrorMessage = "Maximum {0} caractères")]
        public string localisation { get; set; }


        [ScaffoldColumn(false)]
        public DateTime date { get; set; }

        [DisplayName("Client")]
        [Required(ErrorMessage = "Rempliez le champ Client")]
        public int clientid { get; set; }

        [DisplayName("Nom destinateire")]
        [Required(ErrorMessage = "Rempliez le champ le Nom du Destinateire")]
        [MaxLength(100, ErrorMessage = "Maximum {0} caractères")]
        public string nomDestinateire { get; set; }

        [DisplayName("Téléphone destinateire")]
        [Required(ErrorMessage = "Rempliez le champ Téléphone du Destinateire")]
        [MaxLength(13, ErrorMessage = "Maximum {0} caractères")]
        public string telDestinataire { get; set; }

        [DisplayName("Adresse destinateire")]
        [Required(ErrorMessage = "Rempliez le champ l'Adresse du Destinateire")]
        [MaxLength(100, ErrorMessage = "Maximum {0} caractères")]
        public string adresseDestinaraire { get; set; }

        [DisplayName("Ville de depart")]
        public int villeDepartColisid { get; set; }

        [DisplayName("Ville d'arrive")]
        public int villeArriveColisid { get; set; }
        
        [DisplayName("Date Depart")]
        public string dateDepartColis { get; set; }

        
        [DisplayName("Date Arrivé")]
        public string dateArriveColis { get; set; }

        [DisplayName("Voie de transmission")]
        public int voietransmissionid { get; set; }

        */

    }
}

AppWeb/Controllers/ColisController.cs
using AppWeb.ViewModels;
using AutoMapper;
using ClassLibrary;
using Metier.Repository;
using System.Collections.Generic;
using System.Web.Mvc;
using System;

namespace AppWeb.Controllers
{
    public class ColisController : Controller
    {
        VoieTransmissionRepository voiet = new VoieTransmissionRepository();
        ColisRepository ty_ = new ColisRepository();
        ClientRepository cli = new ClientRepository();
        NatureColisRepository nature = new NatureColisRepository();
        VilleRepository ville = new VilleRepository();
        TypeColisRepository tc = new TypeColisRepository();
        EmployeRepository em = new EmployeRepository();
        List<string> d;
        
        // GET: TypeUser
        public ActionResult Index()
        {
            var us = Mapper.Map<List<Colis>, List<ColisViewModel>>(ty_.list());
           
            return View(us);
        }

        public ActionResult Details(int id)
        {
            var us = Mapper.Map<Colis, ColisViewModel>(ty_.findid(id));
            if (us.Colisid == -1)
            {
                return View("Erreur");
            }
           
            return View(us);
                
        }
        public ActionResult Suivre(int id)
        {
            var us = Mapper.Map<Colis, ColisViewModel>(ty_.findid(id));
            if (us.Colisid == -1)
            {
                return View("Erreur");
            }

            return View(us);
        }
        // GET: TypeUser/Create
        public ActionResult Create()
        {
            d = new List<string>();
            d.Add("En preparation");
            d.Add("En Acheminement");
            d.Add("En Livraison");

            ViewBag.Clientid = new SelectList(cli.list(), "Clientid", "nomClient");
            ViewBag.naturecolisid = new SelectList(nature.list(), "NatureColisid", "nomNatureColis");
            ViewBag.typecolisid = new SelectList(tc.list(), "TypeColisid", "nomTypeColis");
            ViewBag.voietransmissionid = new SelectList(voiet.list(), "VoieTransmissionid", "VoieTransmissionNom");
            ViewBag.villeArriveColisid = new SelectList(ville.list(), "Villeid", "nomVille");
            ViewBag.villeDepartColisid = new SelectList(ville.list(), "Villeid", "nomVille");
            ViewBag.etatColis = new SelectList(d);
                
            return View();
        }

        // POST: TypeUser/Create
        [HttpPost]

        public ActionResult Create(ColisViewModel cl)
        {
            cl.date = DateTime.Now;

            if (ModelState.IsValid)
            {
                var us_ = Mapper.Map<ColisViewModel, Colis>(cl);
                ty_.add(us_);

                return RedirectToAction("Index");
            }
            ViewBag.Clientid = new SelectList(cli.list(), "Clientid", "nomClient");
            ViewBag.naturecolisid = new SelectList(nature.list(), "NatureColisid", "nomNatureColis");
            ViewBag.typecolisid = new SelectList(tc.list(), "TypeColisid", "nomTypeColis");
            ViewBag.voietransmissionid = new SelectList(voiet.list(), "VoieTransmissionid", "VoieTransmissionNom");
            ViewBag.villeArriveColisid = new SelectList(ville.list(), "Villeid", "nomVille");
            ViewBag.villeDepartColisid = new SelectList(ville.list(), "Villeid", "nomVille");
            ViewBag.etatColis = new SelectList(d);

            return View(cl);
        }

        // GET: TypeUser/Edit/5
        public ActionResult Edit(int id)
        {
            var us = Mapper.Map<Colis, ColisViewModel>(ty_.findid(id));
            d = new List<string>();
            d.Add("En preparation");
            d.Add("En Acheminement");
            d.Add("En Livraison");
            ViewBag.Clientid = new SelectList(cli.list(), "Clientid", "nomClient",us.clientid);
            ViewBag.naturecolisid = new SelectList(nature.list(), "NatureColisid", "nomNatureColis",us.naturecolisid);
            ViewBag.typecolisid = new SelectList(tc.list(), "TypeColisid", "nomTypeColis",us.typecolisid);
            ViewBag.voietransmissionid = new SelectList(voiet.list(), "VoieTransmissionid", "VoieTransmissionNom",us.voietransmissionid);
            ViewBag.villeArriveColisid = new SelectList(ville.list(), "Villeid", "nomVille",us.villeArriveColisid);
            ViewBag.villeDepartColisid = new SelectList(ville.list(), "Villeid", "nomVille",us.villeDepartColisid);
            ViewBag.etatColis = new SelectList(d,us.etatColis);

            return View(us);
        }

        // POST: TypeUser/Edit/5
        [HttpPost]
        public ActionResult Edit(ColisViewModel cl)
        {
            if (ModelState.IsValid)
            {
                var us = Mapper.Map<ColisViewModel, Colis>(cl);
                ty_.update(us);
                return RedirectToAction("index");
            }
            d = new List<string>();
            d.Add("En preparation");
            d.Add("En Acheminement");
            d.Add("En Livraison");
            ViewBag.Clientid = new SelectList(cli.list(), "Clientid", "nomClient", cl.clientid);
            ViewBag.naturecolisid = new SelectList(nature.list(), "NatureColisid", "nomNatureColis", cl.naturecolisid);
            ViewBag.typecolisid = new SelectList(tc.list(), "TypeColisid", "nomTypeColis", cl.typecolisid);
            ViewBag.voietransmissionid = new SelectList(voiet.list(), "VoieTransmissionid", "VoieTransmissionNom", cl.voietransmissionid);
            ViewBag.villeArriveColisid = new SelectList(ville.list(), "Villeid", "nomVille", cl.villeArriveColisid);
            ViewBag.villeDepartColisid = new SelectList(ville.list(), "Villeid", "nomVille", cl.villeDepartColisid);

            ViewBag.etatColis = new SelectList(d,cl.etatColis);
            return View(cl);
        }

        // GET: TypeUser/Delete/5
        public ActionResult Delete(int id)
        {
            ty_.delete(id);
            return RedirectToAction("index");
        }

    }
}

AppWeb/Views/Colis/Create.cshtml
@model AppWeb.ViewModels.ColisViewModel
<link href="~/Content/css/pikaday.css" rel="stylesheet" />


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h3>Enregistrement Colis</h3>
        <hr />
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.detailsColis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.detailsColis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.detailsColis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.typecolisid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("typecolisid", String.Empty)
                @Html.ValidationMessageFor(model => model.typecolisid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.naturecolisid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
            @Html.DropDownList("naturecolisid", String.Empty)
            @Html.ValidationMessageFor(model => model.naturecolisid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prixColis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prixColis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prixColis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.etatColis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("etatColis", String.Empty)
                @Html.ValidationMessageFor(model => model.etatColis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.localisation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.localisation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.localisation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.clientid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               @Html.DropDownList("Clientid", String.Empty)
             @Html.ValidationMessageFor(model => model.clientid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nomDestinateire, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nomDestinateire, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nomDestinateire, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telDestinataire, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telDestinataire, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telDestinataire, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.adresseDestinaraire, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.adresseDestinaraire, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.adresseDestinaraire, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.villeDepartColisid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
            @Html.DropDownList("villeDepartColisid", String.Empty)
            @Html.ValidationMessageFor(model => model.villeDepartColisid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.villeArriveColisid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
            @Html.DropDownList("villeArriveColisid", String.Empty)
            @Html.ValidationMessageFor(model => model.villeArriveColisid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dateDepartColis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateDepartColis, new { htmlAttributes = new { @class = "form-control", @id = "datepicker" } })
                @Html.ValidationMessageFor(model => model.dateDepartColis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dateArriveColis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateArriveColis, new { htmlAttributes =  new { @id = "datepicker1", @class="form-control" } })
                @Html.ValidationMessageFor(model => model.dateArriveColis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.voietransmissionid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                 @Html.DropDownList("voietransmissionid", String.Empty)
                @Html.ValidationMessageFor(model => model.voietransmissionid, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Liste colis", "Index")
</div>
<script src="~/Content/datetime.js"></script>
<script>

    var picker = new Pikaday(
    {
        field: document.getElementById('datepicker'),
        firstDay: 1,
        minDate: new Date(2000, 0, 1),
        maxDate: new Date(2020, 12, 31),
        yearRange: [2000,2020]
    });

</script>
<script>

    var picker = new Pikaday(
    {
        field: document.getElementById('datepicker1'),
        firstDay: 1,
        minDate: new Date(2000, 0, 1),
        maxDate: new Date(2020, 12, 31),
        yearRange: [2000,2020]
    });

</script>

AppWeb/Views/Colis/Details.cshtml
@model AppWeb.ViewModels.ColisViewModel

<div>
    <h4>Details du Colis</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.detailsColis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.detailsColis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.typecolisid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type.nomTypeColis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.naturecolisid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nature.NomNatureColis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prixColis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prixColis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.etatColis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.etatColis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.localisation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.localisation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.clientid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Client.nomClient)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nomDestinateire)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nomDestinateire)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telDestinataire)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telDestinataire)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.adresseDestinaraire)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.adresseDestinaraire)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.villeDepartColisid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.villeDepartColis.NomVille)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.villeArriveColisid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.villeArriveColis.NomVille)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateDepartColis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateDepartColis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateArriveColis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateArriveColis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.voietransmissionid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Voie.VoieTransmissionNom)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Modifier", "Edit", new { id = Model.Colisid }) |
</p>

AppWeb/Views/Colis/Erreur.cshtml
@model  System.String

<div>
    <h2>ERREUR 404</h2>

    <h3>Le code du colis n'existe pas dans le système</h3>

</div>

AppWeb/Views/Colis/Index.cshtml
@model List<AppWeb.ViewModels.ColisViewModel>

<br />
<h3>Liste des Colis</h3>
<br />
<p>
    @Html.ActionLink("Ajoute Nouveau", "Create")
</p>

<br /><br />
<div class="btn-group-vertical">
    @using (Html.BeginForm("Details", "Colis", FormMethod.Get))
    {
        @Html.DisplayName("Code    ")
        @Html.TextBox("id", "  ")

        <input type="submit" value="Rechercher" />

    }
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model[1].detailsColis)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model[1].prixColis)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[1].etatColis)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[1].localisation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[1].clientid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[1].nomDestinateire)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[1].villeDepartColisid)
        </th>
        
        <th>
            @Html.DisplayName("Date Commandé")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.detailsColis)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.prixColis)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.etatColis)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.localisation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Client.nomClient)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nomDestinateire)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.villeDepartColis.NomVille)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.date)
        </td>
        <td>
            @Html.ActionLink("Modifier", "Edit", new { id=item.Colisid }) |
            @Html.ActionLink("Details", "Details", new { id=item.Colisid }) |
            @Html.ActionLink("Supprimer", "Delete", new { id=item.Colisid })
        </td>
    </tr>
}

</table>

AppWeb/Views/Colis/Suivre.cshtml
@model AppWeb.ViewModels.ColisViewModel

<div>
    <h3>Informations sur le Colis</h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Colisid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Colisid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.detailsColis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.detailsColis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.etatColis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.etatColis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.localisation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.localisation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.clientid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Client.nomClient)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nomDestinateire)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nomDestinateire)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.villeDepartColisid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.villeDepartColis.NomVille)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.villeArriveColisid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.villeArriveColis.NomVille)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateDepartColis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateDepartColis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateArriveColis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateArriveColis)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>